version: "3.9"

services:
  openaigpt-nodejs:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - ${OPENAIGPT_PORT}:${OPENAIGPT_PORT}
    networks:
      - academic-assistant
    command: npx ts-node src/OpenAiGpt.ts

  awspolly-nodejs:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - ${AWS_POLLY_PORT}:${AWS_POLLY_PORT}
    networks:
      - academic-assistant
    command: npx ts-node src/AwsPolly.ts

  awstranscribe-nodejs:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - ${AWS_TRANSCRIBE_PORT}:${AWS_TRANSCRIBE_PORT}
    networks:
      - academic-assistant
    command: npx ts-node src/AwsTranscribe.ts

networks:
  academic-assistant:
    driver: bridge
    external: true
